services:
  pydotbot:
    image: aabadie/pydotbot:latest
    container_name: pydotbot
    restart: unless-stopped
    depends_on:
      - mosquitto
    expose:
      - "8000"
      - "8080"
    environment:
      - CLOUD_MQTT_HOST
      - CLOUD_MQTT_PORT
      - CLOUD_NETWORK_ID
      - MQTT_HOST
      - MQTT_PORT
      - MQTT_WS_PORT
      - MQTT_USE_SSL
      - PIN_CODE_REFRESH_INTERVAL
      - FRONTEND_BASE_URL
  
  swarmit:
    image: aabadie/swarmit:latest
    container_name: swarmit
    restart: unless-stopped
    depends_on:
      - mosquitto
    expose:
      - "8001"
    environment:
      - CLOUD_MQTT_HOST
      - CLOUD_MQTT_PORT
      - CLOUD_NETWORK_ID

  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "1884:1884"
    volumes:
      - ./mosquitto:/mosquitto/config:ro

  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    depends_on:
      - pydotbot
      - swarmit
    ports:
      - "8000:8000"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
